"""add domain column

Revision ID: 7198100adc89
Revises: 
Create Date: 2026-03-09 16:27:13.492707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7198100adc89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_text')
    op.add_column('documents', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'owner_id')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'domain')
    op.create_table('extracted_text',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('extracted_text_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('extracted_text_pkey'))
    )
    # ### end Alembic commands ###
